package com.squirrelplugin;

import com.intellij.psi.TokenType;
import com.intellij.psi.tree.*;

import static com.squirrelplugin.SquirrelTokenTypes.*;

public interface SquirrelTokenTypesSets {
    IFileElementType SQUIRREL_FILE = new IFileElementType("SQUIRRELFILE", SquirrelLanguage.INSTANCE);

    public static final TokenSet WHITE_SPACES = TokenSet.create(TokenType.WHITE_SPACE, WS, NL);

    public static final TokenSet COMMENTS = TokenSet.create(LINE_COMMENT, MULTI_LINE_COMMENT);
    public static final TokenSet SEMICOLONS = TokenSet.create(SEMICOLON, SEMICOLON_SYNTHETIC);

    public static final TokenSet NUMBERS = TokenSet.create(INT, FLOAT);
    public static final TokenSet STRING_LITERALS = TokenSet.create(STRING);

    public static final TokenSet KEYWORDS = TokenSet.create(CONST, ENUM, LOCAL, FUNCTION, CONSTRUCTOR, CLASS, EXTENDS, STATIC, BREAK, CONTINUE, RETURN, YIELD, THROW, FOR, FOREACH, IN, WHILE, DO, IF, ELSE, SWITCH, CASE, DEFAULT, TRY, CATCH, TYPEOF, CLONE, DELETE, RESUME, INSTANCEOF, TRUE, FALSE, NULL);
    public static final TokenSet OPERATORS = TokenSet.create(RBRACE, RBRACKET, RPAREN, PLUS_PLUS, MINUS_MINUS, LBRACE, LBRACKET, LPAREN, DOUBLE_COLON, COLON, SEMICOLON, COMMA, MULTI_ARGS, CLASS_ATTR_START, CLASS_ATTR_END, SHIFT_LEFT, SHIFT_RIGHT, UNSIGNED_SHIFT_RIGHT, CMP, EQ_EQ, NOT_EQ, LESS_OR_EQ, GREATER_OR_EQ, SEND_CHANNEL, PLUS_EQ, MINUS_EQ, MUL_EQ, DIV_EQ, REMAINDER_EQ, OR_OR, AND_AND, EQ, NOT, BIT_NOT, BIT_OR, BIT_XOR, BIT_AND, LESS, GREATER, PLUS, MINUS, MUL, DIV, REMAINDER, QUESTION, AT, DOT);

    public static final TokenSet EXPRESSIONS = TokenSet
            .create(ADDITIVE_EXPRESSION, ARRAY_EXPRESSION, ARRAY_ITEM_EXPRESSION, ASSIGN_EXPRESSION, BITWISE_AND_EXPRESSION, BITWISE_OR_EXPRESSION, BITWISE_XOR_EXPRESSION, CALL_EXPRESSION, CLASS_EXPRESSION, COMMA_EXPRESSION, COMPARE_EXPRESSION, FUNCTION_EXPRESSION, INSTANCE_OF_EXPRESSION, IN_EXPRESSION, LAMBDA_FUNCTION_EXPRESSION, LITERAL_EXPRESSION, LOGIC_AND_EXPRESSION, LOGIC_OR_EXPRESSION, MULTIPLICATIVE_EXPRESSION, PARENTHESIZED_EXPRESSION, PREFIX_EXPRESSION, REFERENCE_EXPRESSION, RELATIONAL_EXPRESSION, SHIFT_EXPRESSION, TABLE_EXPRESSION, TERNARY_EXPRESSION, UNARY_EXPRESSION);

    TokenSet BINARY_EXPRESSIONS = TokenSet.create(
            COMMA_EXPRESSION,
            ASSIGN_EXPRESSION,
            LOGIC_OR_EXPRESSION,
            LOGIC_AND_EXPRESSION,
            IN_EXPRESSION,
            BITWISE_AND_EXPRESSION,
            BITWISE_OR_EXPRESSION,
            BITWISE_XOR_EXPRESSION,
            COMPARE_EXPRESSION,
            RELATIONAL_EXPRESSION,
            SHIFT_EXPRESSION,
            ADDITIVE_EXPRESSION,
            MULTIPLICATIVE_EXPRESSION
    );

    TokenSet LOGIC_OPERATORS = TokenSet.create(
            AND_AND, OR_OR
    );

    TokenSet BITWISE_OPERATORS = TokenSet.create(
            BIT_AND, BIT_OR, BIT_XOR, BIT_NOT
    );

    TokenSet DECLARATIONS = TokenSet.create(
            CLASS_DECLARATION,
            FUNCTION_DECLARATION,
            CONSTRUCTOR_DECLARATION,
            METHOD_DECLARATION,
            VAR_DECLARATION_LIST
    );

    TokenSet FUNCTION_DEFINITION = TokenSet.create(
            FUNCTION_DECLARATION,
            CONSTRUCTOR_DECLARATION,
            METHOD_DECLARATION
    );

    TokenSet BLOCKS = TokenSet.create(
            BLOCK,
            CLASS_MEMBERS,
            SQUIRREL_FILE
    );
}
